import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const vazirmatn = Vazirmatn({
  variable : "--font-vazimatn",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Cat Movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className= {vazirmatn.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
